### ISSUE TITLE
History mechanism breaking on page reload

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#44] opened 2012-02-19 00:17 UTC
The failure occurs in firefox 10.  Visit the nobelists example in the demos directory.  In the viewpanel, select the timeline view.  Reload a few times.  Intermittently, the reloaded page will fail to render it view; apparently the history (saying the timeline view is selected) is persisting over the reload and exhibit is attempting to invoke the timeline view before it has been fully loaded or initialized by the reload.  In particular, at the time of invocation Timline.DefaultEventSource is undefined, so the following error is thrown:

Error: Timeline.DefaultEventSource is not a constructor
Source File: http://api.simile-widgets.org/exhibit/3.0.0rc1/extensions/time/time-extension-bundle.js
Line: 1

**Comment by zepheiryan** [comment] 2012-02-22 19:56
That sounds more like a Timeline loading problem to me, which is basically a duplicate of #35.  I can keep trying to find neat tricks to get around the broken SimileAjax method of loading files, and extension loading definitely need some general work, but at some point #35 has to take place to really make this go away.

**Closed as completed by zepheiryan** 2012-02-22 19:56 UTC

**Comment by karger** [comment] 2012-02-23 01:44
I don't think it's a timeline bug per se.  I think the problem originates from the fact that on reload the selected view stays stuck at view #2 (the timeline view) instead of resetting back to the default view #1.

Or looked at another way, even if there is something wrong with the timeline loader, it seems there may still be a problem with view selection in the history.

**Comment by zepheiryan** [comment] 2012-02-25 00:43
That behavior is a feature, not a bug.  Exhibit retains your place in browsing.

**Comment by latsami** [comment] 2012-07-17 15:41
Hi,
I'm upgrading from 2.2.0 to 3.0.0rc1. I am having the same problem here than Karger. The timeline does load but doesn't interpret all my config (i.e. I have only 2 bands although I am supposed to have 5). How did you fix this Karger?

**Comment by zepheiryan** [comment] 2012-07-17 17:34
Please open a new issue, what you're describing is likely unrelated to this one.  If you could point to your work in progress, that would be extremely helpful.  Thanks.
