### ISSUE TITLE
History breaks in IE9

### ISSUE THREAD

**Issue by jutulen** [zepheira/exhibit3#100] opened 2012-10-18 21:28 UTC
In Internet Explorer 9 the history functionality breaks.  If I click to select a different View (maps, tiles, table, etc.) the URL in the address window adds a # after the file name and what appears to be a session id.  For example:

/index3.html#./index3.html?&_suid=1350594535370007020790095611534 

When I try to click on anything on the page I get this error in IE9:

SCRIPT5022: History.js does not support states with fragement-identifiers (hashes/anchors). 
jquery.history.js, line 1 character 6203

**Comment by avoinea** [comment] 2013-03-11 13:31
Any idea how to fix this?

**Comment by karger** [comment] 2013-03-24 04:29
I've got some info about the problem though no idea how to fix it.  exhibit's pushstate method invokes the history.js library, which in turn is supposed to trigger a statechange event that the exhibit controls listen for to rerender themselves.  However, the logic of the history.js library in ie9 results in its returning without triggering statechange---I'm not sure why.  

not sure if this is this a regression or has always been broken.

**Comment by michaeljonathanblack** [comment] 2013-04-03 02:35
If anyone has discovered a solution to this, I would love to hear it. Otherwise it looks like I'll be reimplementing all of this without History, which sounds really unfortunate at this point.

**Comment by karger** [comment] 2013-04-03 05:09
I've been working at this but haven't yet figured out why it's going 
wrong.  the obvious easy fix is to disable history, but I'm not sure 
that exhibit actually supports this right now.  View updates are 
triggered by state change events, and state change events are only 
triggered by the history mechanism.  So it isn't clear how to get by 
without history.

I suspect the problem will go away in IE10, which supports html5 
history api.

**Comment by jannaee** [comment] 2013-07-03 18:21
I'm running into the same issue now. Is there any progress on this? I'm pretty much a newb at coding and I don't know where to start to try and fix this. We are using the replaceState method, and the same thread comes back with a #./ inserted into the URL. 

I've seen a few types of solutions but none are seem to work. If you don't have the fix, then are there any graceful degradation/fallback code suggestions that will allow me to keep the history and just remove the #?

**Comment by karger** [comment] 2013-07-03 18:47
I'm aware of the problem and have been trying to get to the bottom of 
it on and off for weeks. Unfortunately the code involved is highly 
asynchronous/event driven, and most of my attempts to trace things in 
debug mode make the problem go away.  If anyone is familiar with 
history.js and can provide insight, I'd love some help; meanwhile I 
will keep trying.

**Comment by michaeljonathanblack** [comment] 2013-07-03 19:01
I use History.js in the Historical Weather piece of the Energy Trader. Is
that why I was included on this email? Feel free to check out Historical.js
in the Widgets folder of that project and see what I do there. As far as I
know, it works with IE9.

**Comment by karger** [comment] 2013-07-03 21:47
Yes, I assume history.js works with IE9 or there would be more complaints as it is widely used.  However, it isn't working with the exhibit codebase.  Tracing its execution takes me to some code that doesn't make a lot of sense; does anyone know if there is any history.js documentation (beyond the code) that explains what it is doing?

**Comment by JonnyMe** [comment] 2013-07-23 15:01
I made a simple workaround for supply this problem. On page load I check if page url is the same as i expect (like http://example.com/something) and if not (like http://example.com/something#./something?&_suid=.....) I reload the page with a default value (set for example at http://example.com/something).

It is not a fix and you will loose all elements selected but makes IE not triggering errors anymore.

``` javascript
var correctURL = "/something";
var domainPrefix = location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '');

var currentLocation = location.href;
var correctLocation = domainPrefix + correctURL;

if(currentLocation != correctLocation){
    location.href = correctLocation;
}
```

**Comment by JonnyMe** [comment] 2013-07-24 07:51
And I forgot to mention that I replaced jquery.history.js with this version:

[https://github.com/browserstate/history.js/blob/master/scripts/bundled-uncompressed/html4%2Bhtml5/jquery.history.js](https://github.com/browserstate/history.js/blob/master/scripts/bundled-uncompressed/html4%2Bhtml5/jquery.history.js)

**Comment by karger** [comment] 2013-07-24 09:00
I've made what might be a more complete fix, currently serving from 
http://people.csail.mit.edu/karger/ExhibitK/dist/ .   Can you let me 
know if it works for you?

**Comment by JonnyMe** [comment] 2013-07-24 13:11
Unfortunately now I can only try on IE8 and the version you linked doesn't
work properly. My situation is a map with multiple markers of different
types with a simple facet for filtering. What happens with your version is
that when I press on a filter label it triggers only suid update but
nothing changes on page until I refresh. When I refresh page I can see the
selection I made.

2013/7/24 David Karger notifications@github.com

**Comment by karger** [comment] 2013-08-18 03:08
I made some additional corrections, possibly after you tried.  Can you 
try again and let me know what happens?  Others have reported success on 
IE8.  The fix has been pushed to 
http://api.simile-widgets.org/exhibit/HEAD/ if you want to try linking 
to that.  If it still doesn't work for you, please post a link to the 
broken exhibit.

**Comment by zepheiryan** [comment] 2013-08-22 00:03
You're free to keep discussing here if need be, but it sounds like this issue is potentially solved, and as mentioned earlier, it generally deals with a different code base.  Closing.

**Closed as completed by zepheiryan** 2013-08-22 00:03 UTC
Labels: Bug, Priority:Intermediate

**Comment by karger** [comment] 2013-08-22 04:06
Note that the proposed solution is here: https://github.com/simile-widgets/exhibit/pull/15
